import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const PrivacyPolicy = () => {
  return (
    <>
      <Navbar />
      <main className="pt-28 pb-20">
        <div className="container mx-auto px-6 max-w-3xl">
          <h1 className="font-display text-4xl md:text-5xl font-bold text-foreground mb-2">
            Privacy Policy for LEWAY Creatives
          </h1>
          <p className="font-body text-sm text-muted-foreground mb-12">
            Last updated: February 15, 2026
          </p>

          <div className="prose prose-sm max-w-none font-body text-muted-foreground space-y-8 [&_h2]:font-display [&_h2]:text-foreground [&_h2]:text-xl [&_h2]:font-bold [&_h2]:mt-12 [&_h2]:mb-4 [&_h3]:font-display [&_h3]:text-foreground [&_h3]:text-lg [&_h3]:font-semibold [&_h3]:mt-8 [&_h3]:mb-3 [&_ul]:list-disc [&_ul]:pl-6 [&_ul]:space-y-2 [&_p]:leading-relaxed [&_a]:text-primary [&_a]:underline [&_a]:underline-offset-2 hover:[&_a]:text-primary/80">
            <p>
              This Privacy Policy describes Our policies and procedures on the collection, use, and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
            </p>
            <p>
              We use Your Personal Data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.
            </p>

            <h2>1. Interpretation and Definitions</h2>

            <h3>Interpretation</h3>
            <p>
              The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
            </p>

            <h3>Definitions</h3>
            <p>For the purposes of this Privacy Policy:</p>
            <ul>
              <li><strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to LEWAY Creatives, a business entity registered in Kenya.</li>
              <li><strong>Website</strong> refers to Leway Creatives, accessible from <a href="https://lewaycreatives.com/" target="_blank" rel="noopener noreferrer">https://lewaycreatives.com/</a>.</li>
              <li><strong>Service</strong> refers to the Website and all services offered by the Company, including but not limited to Web Design &amp; Development, Graphic &amp; Creative Design, Content Creation &amp; Copywriting, and Career &amp; Personal Branding.</li>
              <li><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</li>
              <li><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
              <li><strong>Country</strong> refers to: Kenya.</li>
              <li><strong>Device</strong> means any device that can access the Service such as a computer, a cell phone or a digital tablet.</li>
              <li><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.</li>
              <li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</li>
              <li><strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</li>
            </ul>

            <h2>2. Collecting and Using Your Personal Data</h2>

            <h3>Types of Data Collected</h3>
            <ul>
              <li><strong>Personal Data:</strong> While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. This may include, but is not limited to:
                <ul>
                  <li>Email address</li>
                  <li>First name and last name</li>
                  <li>Phone number</li>
                </ul>
              </li>
              <li><strong>Client Project Data:</strong> To provide our services, especially for Career &amp; Personal Branding (e.g., ATS-Optimized Resumes, LinkedIn Profile Optimization), We may collect professional and career-related information that You voluntarily provide, such as your employment history, skills, and educational background. This information is used exclusively to fulfill the contracted service.</li>
              <li><strong>Usage Data:</strong> Usage Data is collected automatically when using the Service. This may include information such as Your Device's IP address, browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, and other diagnostic data.</li>
              <li><strong>Tracking Technologies and Cookies:</strong> We use Cookies and similar tracking technologies like web beacons to track activity on Our Service, improve user experience, and for analytics and marketing purposes. You can manage your cookie preferences through your browser settings.</li>
            </ul>

            <h3>How We Use Your Personal Data</h3>
            <p>The Company may use Personal Data for the following purposes:</p>
            <ul>
              <li>To provide and maintain our Service, including the fulfillment of services such as website design, content creation, and resume writing.</li>
              <li>To manage Your requests and to communicate with You about your projects and inquiries.</li>
              <li>For the performance of a contract: To develop, comply with, and undertake the purchase contract for the services You have purchased.</li>
              <li>To contact You by email or phone with updates or informative communications related to the services you have engaged us for.</li>
              <li>To provide You with news and promotional offers about our services, such as special promotions on landing pages or new graphic design packages, unless You have opted not to receive such information.</li>
              <li>For remarketing and advertising purposes to present you with relevant ads on third-party websites.</li>
              <li>For other business purposes, such as data analysis, identifying usage trends, and determining the effectiveness of our promotional campaigns to improve our Service.</li>
            </ul>

            <h2>3. Third-Party Service Providers</h2>
            <p>We share your information with trusted third-party Service Providers to perform specific functions for Our business. These include:</p>
            <ul>
              <li><strong>Analytics:</strong> We use Google Analytics to monitor and analyze the use of our Service. Google's Privacy Policy can be found here: <a href="https://policies.google.com/privacy" target="_blank" rel="noopener noreferrer">https://policies.google.com/privacy</a>.</li>
              <li><strong>Email Marketing:</strong> We use Mailchimp to send newsletters and marketing emails. You can review Mailchimp's privacy policy for more information: <a href="https://mailchimp.com/legal/privacy/" target="_blank" rel="noopener noreferrer">https://mailchimp.com/legal/privacy/</a>.</li>
              <li><strong>Payment Processing:</strong> We process payments for our services via Bank Transfer. We do not collect or store your bank account or payment card information. We only receive information necessary to confirm your payment.</li>
              <li><strong>Remarketing Services:</strong> We use Google Ads (AdWords) and Facebook remarketing services to advertise our business. These services use cookies to serve ads based on your past visits to our Website.
                <ul>
                  <li>You can opt-out of Google's use of cookies by visiting the Google Ad Settings page.</li>
                  <li>You can manage your Facebook advertising preferences through your Facebook account settings.</li>
                </ul>
              </li>
            </ul>

            <h2>4. Transfer and Retention of Your Personal Data</h2>
            <p>
              Your information is processed at the Company's operating offices in Kenya. It may be transferred to — and maintained on — computers located outside of Your jurisdiction where data protection laws may differ. We will take all steps reasonably necessary to ensure that Your data is treated securely.
            </p>
            <p>
              The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy, and to comply with our legal obligations.
            </p>

            <h2>5. Disclosure of Your Personal Data</h2>
            <p>We do not sell your Personal Data. We may disclose your Personal Data in the good faith belief that such action is necessary to:</p>
            <ul>
              <li>Comply with a legal obligation.</li>
              <li>Protect and defend the rights or property of the Company.</li>
              <li>Prevent or investigate possible wrongdoing in connection with the Service.</li>
              <li>Protect the personal safety of Users of the Service or the public.</li>
              <li>In connection with a business transaction such as a merger or asset sale.</li>
            </ul>

            <h2>6. Security of Your Personal Data</h2>
            <p>
              The security of Your Personal Data is important to Us. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.
            </p>

            <h2>7. Your Data Protection Rights</h2>

            <h3>General Data Protection Regulation (GDPR) Compliance</h3>
            <p>
              If you are a resident of the European Economic Area (EEA), you have certain data protection rights. We aim to take reasonable steps to allow you to correct, amend, delete, or limit the use of your Personal Data. Your rights under GDPR include:
            </p>
            <ul>
              <li>The right to access, update or delete the information we have on you.</li>
              <li>The right of rectification.</li>
              <li>The right to object.</li>
              <li>The right of restriction.</li>
              <li>The right to data portability.</li>
              <li>The right to withdraw consent.</li>
            </ul>

            <h3>Kenya Data Protection Act (DPA) 2019 Compliance</h3>
            <p>
              As a business operating in Kenya, we are compliant with the DPA. If you are a resident of Kenya, your rights include:
            </p>
            <ul>
              <li>The right to be informed of the use to which your personal data is to be put.</li>
              <li>The right to access your personal data.</li>
              <li>The right to object to the processing of all or part of your personal data.</li>
              <li>The right to the correction of false or misleading data.</li>
              <li>The right to the deletion of false or misleading data about you.</li>
            </ul>
            <p>To exercise any of these rights, please contact us using the information provided below.</p>

            <h2>8. Children's Privacy</h2>
            <p>
              Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from children under 13.
            </p>

            <h2>9. Links to Other Websites</h2>
            <p>
              Our Service may contain links to other websites that are not operated by Us, such as our Facebook Fan Page (<a href="https://www.facebook.com/leway-creatives" target="_blank" rel="noopener noreferrer">https://www.facebook.com/leway-creatives</a>). If You click on a third-party link, We strongly advise You to review the Privacy Policy of every site You visit.
            </p>

            <h2>10. Changes to this Privacy Policy</h2>
            <p>
              We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page and updating the "Last updated" date.
            </p>

            <h2>11. Contact Us</h2>
            <p>
              If you have any questions about this Privacy Policy, You can contact us by visiting this page on our website: <a href="https://lewaycreatives.com/contact-us">https://lewaycreatives.com/contact-us</a>
            </p>
          </div>
        </div>
      </main>
      <Footer />
    </>
  );
};

export default PrivacyPolicy;
